### ISSUE TITLE
Release YAActL v0.3

### ISSUE THREAD

**Issue by pbayer** [pbayer/YAActL.jl#17]
This issue collects what should be in v0.3. Emphasis is on error handling, but a lot of other improvements should go into it as well. The work should be organized into several minor releases:

## v0.2.1, Actor Registry

- [x] Close issue #10, strong isolation of actors
- [x] Close issue #12, actor registry 
- [x] register v0.2.1 

## v0.2.2, Actor Improvements

- [x] simplify actor dispatch on `Query` and `Update` with `getfield` and `setfield!` see issue #16, 
- [ ] Close issue #10: Safe parallel actor startup 
- [ ] Close issue #15: support functional object
- [ ] Close issue #11: Controlled Actor Termination
- [ ] Implement Actor Task, see issue #16
- [ ] register v0.2.2 

## v0.2.3, Supervision Tree

- [ ] Close  issue #7: supervision tree 
- [ ] register v0.2.3

## v0.3.0. Error handling

- [ ] Increase test coverage
- [ ] Complete documentation
- [ ] Realistic examples (examples must reflect application scope)
- [ ] register v0.3
- [ ] announce on Discourse

**Comment by pbayer** [comment]
## `YAActL` v0.2.1 

- stronger actor isolation
- actor registry

@JuliaRegistrator register

**Comment by pbayer** [comment]
This won't be done in `YAActL`.  The next development stage will be done in `Actors`.
